import Link from "next/link"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { FileText, Video, Download, ExternalLink, Book, HelpCircle } from "lucide-react"

const resources = [
  {
    category: "guides",
    items: [
      {
        title: "Getting Started with ICXP",
        description: "A comprehensive guide for new users on how to use the ICXP platform.",
        type: "PDF",
        link: "#",
      },
      {
        title: "Carbon Credit Basics",
        description: "Learn the fundamentals of carbon credits and how they work.",
        type: "Article",
        link: "#",
      },
      {
        title: "Project Development Handbook",
        description: "A step-by-step guide to developing carbon credit projects.",
        type: "PDF",
        link: "#",
      },
    ],
  },
  {
    category: "tutorials",
    items: [
      {
        title: "How to List Your First Project",
        description: "A video tutorial on listing your carbon credit project on ICXP.",
        type: "Video",
        link: "#",
      },
      {
        title: "Understanding Verification Process",
        description: "An in-depth look at the project verification process.",
        type: "Video",
        link: "#",
      },
      {
        title: "Trading on ICXP Marketplace",
        description: "Learn how to buy and sell carbon credits on our platform.",
        type: "Article",
        link: "#",
      },
    ],
  },
  {
    category: "reports",
    items: [
      {
        title: "Australian Carbon Market Report 2023",
        description: "Annual report on the state of the Australian carbon market.",
        type: "PDF",
        link: "#",
      },
      {
        title: "Global Carbon Credit Trends",
        description: "Analysis of global trends in carbon credit trading.",
        type: "PDF",
        link: "#",
      },
      {
        title: "Impact of Co-benefits on Credit Valuation",
        description: "Research on how co-benefits affect carbon credit prices.",
        type: "Article",
        link: "#",
      },
    ],
  },
]

const faqs = [
  {
    question: "What are carbon credits?",
    answer:
      "Carbon credits are tradable certificates representing the right to emit one tonne of carbon dioxide or equivalent greenhouse gas. They are generated by projects that reduce, remove, or avoid greenhouse gas emissions.",
  },
  {
    question: "How does ICXP ensure the credibility of carbon credits?",
    answer:
      "ICXP uses blockchain technology for transparent tracking and employs AI and remote sensing for efficient verification. We also partner with respected environmental organizations and adhere to international standards.",
  },
  {
    question: "Can small-scale projects participate in ICXP?",
    answer:
      "ICXP is designed to be inclusive, with simplified onboarding processes and aggregated projects to lower costs and increase scalability for small-scale participants.",
  },
  {
    question: "What types of projects are eligible for carbon credits on ICXP?",
    answer:
      "Eligible projects include reforestation, renewable energy, energy efficiency, methane capture, and more. We welcome innovative projects that demonstrably reduce or remove greenhouse gas emissions.",
  },
  {
    question: "How are co-benefits recognized and valued on ICXP?",
    answer:
      "ICXP highlights and monetizes co-benefits such as biodiversity protection and community development. Projects with significant co-benefits may command premium prices in our marketplace.",
  },
]

export default function ResourcesPage() {
  return (
    <main id="main-content" className="container py-8 space-y-12">
      <h1 className="text-4xl font-bold mb-6">Resources</h1>
      <p className="text-xl text-muted-foreground mb-8">
        Explore our collection of guides, tutorials, and reports to help you navigate the carbon credit market and make
        the most of the ICXP platform.
      </p>

      <Tabs defaultValue="guides" className="space-y-8">
        <TabsList>
          <TabsTrigger value="guides">Guides</TabsTrigger>
          <TabsTrigger value="tutorials">Tutorials</TabsTrigger>
          <TabsTrigger value="reports">Reports</TabsTrigger>
          <TabsTrigger value="faq">FAQ</TabsTrigger>
        </TabsList>

        {resources.map((category) => (
          <TabsContent key={category.category} value={category.category} className="space-y-6">
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              {category.items.map((resource, index) => (
                <Card key={index}>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      {resource.type === "PDF" && <FileText className="h-5 w-5" />}
                      {resource.type === "Video" && <Video className="h-5 w-5" />}
                      {resource.type === "Article" && <FileText className="h-5 w-5" />}
                      {resource.title}
                    </CardTitle>
                    <CardDescription>{resource.description}</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Button variant="outline" asChild className="w-full">
                      <Link href={resource.link}>
                        {resource.type === "PDF" ? (
                          <>
                            <Download className="mr-2 h-4 w-4" />
                            Download PDF
                          </>
                        ) : (
                          <>
                            <ExternalLink className="mr-2 h-4 w-4" />
                            View {resource.type}
                          </>
                        )}
                      </Link>
                    </Button>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>
        ))}

        <TabsContent value="faq">
          <div className="space-y-6">
            {faqs.map((faq, index) => (
              <Card key={index}>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <HelpCircle className="h-5 w-5" />
                    {faq.question}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p>{faq.answer}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>
      </Tabs>

      <section>
        <h2 className="text-3xl font-semibold mb-6">Need More Help?</h2>
        <Card>
          <CardContent className="flex flex-col md:flex-row justify-between items-center p-6">
            <div className="mb-4 md:mb-0">
              <h3 className="text-2xl font-semibold mb-2">Contact Our Support Team</h3>
              <p className="text-muted-foreground">
                Our experts are ready to assist you with any questions or concerns.
              </p>
            </div>
            <Button size="lg" asChild>
              <Link href="/contact">Get in Touch</Link>
            </Button>
          </CardContent>
        </Card>
      </section>
    </main>
  )
}

