"use client"

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

const faqs = [
  {
    question: "What are carbon credits?",
    answer:
      "Carbon credits are tradable certificates representing the right to emit one tonne of carbon dioxide or equivalent greenhouse gas. They are generated by projects that reduce, remove, or avoid greenhouse gas emissions.",
  },
  {
    question: "How does ICXP ensure the credibility of carbon credits?",
    answer:
      "ICXP uses blockchain technology for transparent tracking and employs AI and remote sensing for efficient verification. We also partner with respected environmental organizations and adhere to international standards.",
  },
  {
    question: "Can small-scale projects participate in ICXP?",
    answer:
      "ICXP is designed to be inclusive, with simplified onboarding processes and aggregated projects to lower costs and increase scalability for small-scale participants.",
  },
  {
    question: "What types of projects are eligible for carbon credits on ICXP?",
    answer:
      "Eligible projects include reforestation, renewable energy, energy efficiency, methane capture, and more. We welcome innovative projects that demonstrably reduce or remove greenhouse gas emissions.",
  },
  {
    question: "How are co-benefits recognized and valued on ICXP?",
    answer:
      "ICXP highlights and monetizes co-benefits such as biodiversity protection and community development. Projects with significant co-benefits may command premium prices in our marketplace.",
  },
]

export function FAQ() {
  return (
    <Accordion type="single" collapsible className="w-full">
      {faqs.map((faq, index) => (
        <AccordionItem key={index} value={`item-${index}`}>
          <AccordionTrigger>{faq.question}</AccordionTrigger>
          <AccordionContent>{faq.answer}</AccordionContent>
        </AccordionItem>
      ))}
    </Accordion>
  )
}

